# Site settings - Updated for AI Workshop Series
title: "AI Musings"
description: "Accelerate Your AI Game: Learn, Build, Apply in One Immersive Session - Hands-on AI workshops for professionals, coaches, consultants, entrepreneurs, and business owners"
url: "https://aimusings.space"
baseurl: ""

# Contact and Social Information
contact:
  email: "spradhip@pulsarventurs.co"
  calendly: "https://calendly.com/spradhip"
  linkedin: "https://www.linkedin.com/company/pulsar-ventures-llc"
  office_hours:
    weekdays: "9:00 AM - 6:00 PM (EST)"
    weekends: "By appointment"
    virtual: "Available worldwide"

# Author information
author:
  name: "AI Musings"
  email: "spradhip@pulsarventurs.co"
  bio: "Hands-on AI workshops designed for professionals who want to transform their work with practical AI skills"
  location: "Global"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/company/pulsar-ventures-llc"
    - label: "Calendly"
      icon: "fas fa-calendar"
      url: "https://calendly.com/spradhip"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
relative_links:
  enabled: true
  collections: true

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AI Musings"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "AI Musings"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .github/
  - README.md

# Include files
include:
  - _pages
  - _posts
  - assets
  - _sass

# Social media
social:
  name: "AI Musings"
  links:
    - "https://www.linkedin.com/company/pulsar-ventures-llc"
    - "https://calendly.com/spradhip"

# Analytics (add your tracking codes here)
analytics:
  google: ""  # Add your Google Analytics ID
  facebook: ""  # Add your Facebook Pixel ID

# Comments (optional)
comments:
  provider: ""  # Add comment system provider

# Search
search: true

# Timezone
timezone: "UTC"

# Encoding
encoding: utf-8

# Future posts
future: false

# Show drafts
show_drafts: false

# Limit posts
limit_posts: 0

# Keep files
keep_files:
  - .git
  - .github
  - CNAME
